name: Inspection

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Trigger shipjs]
    types:
      - completed

jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '1' $GITHUB_REF
          echo '1' $GITHUB_REF
