name: Trigger shipjs
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Trigger shipjs
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'releases/v') && github.base_ref == 'main'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: "lts/*"
      - run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - run: git switch main
      - run: npm install --ignore-scripts
      - run: npm run release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
